#
# Copyright (C) 2020 Jakub Ksiezniak
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License along
#     with this program; if not, write to the Free Software Foundation, Inc.,
#     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# The java.util.logging configuration, loaded by the Launcher
handlers=java.util.logging.ConsoleHandler

# Default logging detail level
.level=INFO

# FINEST shows every packet
#xpra.protocol.XpraSender.level=FINEST
xpra.protocol.XpraReceiver.level=FINEST

java.util.logging.ConsoleHandler.level=ALL
# ie: "INFO xpra.client.XpraClient: Connected to Xpra server version 6.3"
java.util.logging.SimpleFormatter.format=%4$s %3$s: %5$s%6$s%n
